spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true



api : 
  kakao:
    key: "k1_YmUKHxl8R0uo45qEnaruqwt146aJMZquxZq9cCj1zTgAAAYcJitK"
  naver:
    url : "https://openapi.naver.com/v1/search/local.xml"
    clientId : "8uPRnfPwQRlqM7Aruxsz"
    clientSecret : "DdiMLUcias"